language: node_js
node_js:
 - 0.10
notifications:
 - adolfo.brunno.ba@gmail.com
before_install:
 - npm install -g bower
 - npm install -g grunt-cli
 - npm install -g karma-cli
 - npm install -g protractor
 - webdriver-manager update
 - bower install
before_script:
 - node test/data.js
 - grunt
 - cd dist
env:
 global:
  - NODE_ENV: test
addons:
 sauce_connect: true
services:
 - mongodb
script:
 - karma start config/karma.config.js --single-run --browsers PhantomJS
 - node server &
 - protractor config/protractor.js